name: My Custom Workflow

on:
    workflow_dispatch: 
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Install Dependency
              run: npm install @actions/core moment
            - name: Run custom action
              uses: Mittal-Shivam/custom-actions@main