name: environment-deploy-workflow
on:
    workflow_dispatch: 

env:
    NODE_VERSION: '18.x'

jobs:
    install-build-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Use Node
              uses: actions/setup-node@v3
              with:
                node-version: ${{env.NODE_VERSION}}
                cache: 'npm'

            - name: Install, Build and Test
              run: |
                npm ci
                npm run build --if-present
                npm test

    deploy_staging:
        runs-on: ubuntu-latest
        needs: install-build-test
        environment: 
            name: staging

        steps:
            - name: Deploy to staging
              run: |
                echo "Deployed to staging environment"

    deploy_production:
        runs-on: ubuntu-latest
        needs: deploy_staging
        environment: 
            name: production

        steps:
            - name: Deploy to production
              run: |
                echo "Deployed to production environment"

    