name: Parallel Workflow

on:
    workflow_dispatch: 
    push:
        branches:
            - main
    pull_request: 
        branches: 
            - main
    # Scheduled trigger at 5:00 AM UTC, Monday through Friday
    schedule:
      - cron: '0 5 * * 1-5'

jobs:
    build-and-test-1:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v3

            - name: Use Node.js latest
              uses: actions/setup-node@v3
              with:
                node-version: latest

            - name: Print a message for main branch
              if: github.ref == 'refs/heads/main'
              run: echo 'This is main branch'

            - name: Print a message for non-main branch
              if: github.ref != 'refs/heads/main'
              run: echo 'This is not main branch'
            
            - name: Debug message
              if: env.DEBUG == 'true'
              run: echo "Debugging enabled"

    build-and-test-2:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v3

            - name: Use Node.js latest
              uses: actions/setup-node@v3
              with:
                node-version: latest

            - name: Print a message for main branch
              if: github.ref == 'refs/heads/main'
              run: echo 'This is main branch'

            - name: Print a message for non-main branch
              if: github.ref != 'refs/heads/main'
              run: echo 'This is not main branch'
            
            - name: Debug message
              if: env.DEBUG == 'true'
              run: echo "Debugging enabled"

    post-build-actions:
        needs: [build-and-test-1, build-and-test-2]
        runs-on: ubuntu-latest
        steps:
          - name: Publish test results
            uses: actions/upload-artifact@v3
            with:
                name: test-results
                path: test-results.xml
